## 교수 및 전공정보 추출분석

In [1]:
import os
import numpy as np
import pandas as pd
from IPython import display

pd.options.display.max_rows = 999 # 데이터 프레임 표시 최대 열수를 999로 지정
pd.set_option('display.max_columns',999) # 데이터 프레임 표시 최대 행수를 999로 지정

In [2]:
# get excel data to dataframe
get_file = './college_datasets/UC Berkeley/Professors 전공정보 및 General 대학 정보 링크 - UC Berkeley.csv'

df = pd.read_csv(get_file)
df

,Professor,First Major,Second Major,Third Major,Fourth Major,Fifth Major,"General Info/Bio, Research & Publications",Other Academic information,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Aaron Fisher,Psychology,NaN,NaN,NaN,NaN,Research Expertise and Interest\nIdiographic s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aaron Parsons,Astrophysics,NaN,NaN,NaN,NaN,Research Expertise and Interest\ncosmic reioni...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aaron S. Edlin,Economics,NaN,NaN,NaN,NaN,"Research Expertise and Interest\neconomics, in...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aaron Streets,Bioengineering,Bioengineering and Business Administration,Bioengineering/Materials Science and Engineeri...,NaN,NaN,Research Expertise and Interest\nbiological sy...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abby Dernburg,Molecular and Cell Biology,NaN,NaN,NaN,NaN,Research Expertise and Interest\nchromosome re...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1116,Yuriy Gorodnichenko,Economics,NaN,NaN,NaN,NaN,Research Expertise and Interest\nmacroeconomics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117,Yury G. Kolomensky,Physics,NaN,NaN,NaN,NaN,Research Expertise and Interest\nparticle phys...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1118,Zi Q. Qiu,Physics,NaN,NaN,NaN,NaN,Research Expertise and Interest\nExperimental ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1119,Zuo-Jun Max Shen,Civil Engineering,NaN,NaN,NaN,NaN,"Research Expertise and Interest\nlogistics, su...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1120,Zuo-Jun Shen,Industrial Engineering and Operations Research,Industrial Engineering and Operations Research...,Operations Research and Management Science,NaN,NaN,"Research Expertise and Interest\nlogistics, su...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# 소문자로 변환
df['Professor'] = df['Professor'].astype(str).str.lower()
df['First Major'] = df['First Major'].astype(str).str.lower()
df['Second Major'] = df['Second Major'].astype(str).str.lower()
df['Third Major'] = df['Third Major'].astype(str).str.lower()
df['Fourth Major'] = df['Fourth Major'].astype(str).str.lower()
df['Fifth Major'] = df['Fifth Major'].astype(str).str.lower()
df['General Info/Bio, Research & Publications'] = df['General Info/Bio, Research & Publications'].astype(str).str.lower()
df['Other Academic information'] = df['Other Academic information'].astype(str).str.lower()
df

,Professor,First Major,Second Major,Third Major,Fourth Major,Fifth Major,"General Info/Bio, Research & Publications",Other Academic information,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,aaron fisher,psychology,nan,nan,nan,nan,research expertise and interest\nidiographic s...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,aaron parsons,astrophysics,nan,nan,nan,nan,research expertise and interest\ncosmic reioni...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,aaron s. edlin,economics,nan,nan,nan,nan,"research expertise and interest\neconomics, in...",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,aaron streets,bioengineering,bioengineering and business administration,bioengineering/materials science and engineeri...,nan,nan,research expertise and interest\nbiological sy...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,abby dernburg,molecular and cell biology,nan,nan,nan,nan,research expertise and interest\nchromosome re...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1116,yuriy gorodnichenko,economics,nan,nan,nan,nan,research expertise and interest\nmacroeconomics,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117,yury g. kolomensky,physics,nan,nan,nan,nan,research expertise and interest\nparticle phys...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1118,zi q. qiu,physics,nan,nan,nan,nan,research expertise and interest\nexperimental ...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1119,zuo-jun max shen,civil engineering,nan,nan,nan,nan,"research expertise and interest\nlogistics, su...",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1120,zuo-jun shen,industrial engineering and operations research,industrial engineering and operations research...,operations research and management science,nan,nan,"research expertise and interest\nlogistics, su...",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# 입학을 원하는 학교, 학과, 희망전공, 에세이를 입력하면 여기서 DB에서 내용을 추출하여 보여준다.
# 대학별/전공별 페이지에 display 되는 word cloud
# A. 각 대학별로 최신 keyword 가 어떻게 되는00000지 정리 - news 또는 SNS 빅데이터 기반의 word cloud 제공
# B. 각 대학의 전공별 keyword word cloud 제공 - 대학 전공별로 모아놓은 정보 활용